# Ativar com: ./mvnw spring-boot:run -Dspring-boot.run.profiles=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/reportai
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.h2.console.enabled=false
